from turtle import *
import grass_blades
import brown_building
import turtle_trees
import turtle_car
import turtle_clouds
import turtle_birds
speed(300)
color('light blue')
goto(-200, -200)
begin_fill()
for i in range(4):
    forward(400)
    left(90)
end_fill()
left(90)
color('light green')
begin_fill()
forward(100)
right(90)
forward(400)
right(90)
forward(100)
right(90)
forward(400)
end_fill()
#Grass Blades
penup()
left(-90)
forward(75)
left(-90)
forward(2)
left(-45)
pendown()
grass_blades.grass_blades(14)
penup()
goto(-198, -175)
pendown()
grass_blades.grass_blades(14)
#Trees
penup()
goto(-200, -100)
right(360-135+90)
forward(15)
pendown()
for i in range(15):
    turtle_trees.trees()
#Brown Building
penup()
right(90)
goto(-175,-180)
back(75)
right(0)
back(-50)
right(-90)
pendown()
brown_building.brown_building()
#Cars
penup()
right(180)
forward(50)
pendown()
turtle_car.car('red')
penup()
goto(0,-150)
turtle_car.car('blue')
#Sun
penup()
goto(125,75)
pendown()
color('orange', 'yellow')
begin_fill()
circle(50)
end_fill()
#Clouds
penup()
goto(0,80)
pendown()
turtle_clouds.clouds()
penup()
forward(55)
right(90)
forward(50)
pendown()
left(90)
turtle_clouds.clouds()
#Birds
def bird_andlocation(x,y):
    penup()
    goto(x,y)
    pendown()
    color('black')
    turtle_birds.birds()
    left(90)
bird_andlocation(50,75)
bird_andlocation(30,50)
bird_andlocation(25,85)
bird_andlocation(-50,60)
bird_andlocation(-88,50)
bird_andlocation(-100,75)
bird_andlocation(0,54)
bird_andlocation(-57,80)
hideturtle()
exitonclick()
